# Copyright (c) 2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set cuda_spec = ">=" + cuda_major ~ ",<" + (cuda_major | int + 1) ~ ".0a0" %} # i.e. >=11,<12.0a0
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: rapids_dependencies

outputs:
  - name: rapids_cupy_dependency
    version: {{ version }}
    requirements:
      run:
        - cupy >=12
  - name: rapids_numpy_dependency
    requirements:
      run:
        - numpy >=1.21
  - name: rapids_numba_dependency
    requirements:
      run:
        - numba >=0.56.4,<0.57
  - name: rapids_cuda_python_dependency
    requirements:
      host:
        - cuda-version == {{ cuda_version }}
      run: 
        # Note that this will require building for multiple CUDA versions
        - pin_compatible("cuda-version", min_pin="x", max_pin="x")
        {% if cuda_version.split('.')[0] == 1 %}
        - cuda-python >=11.7.1,<12
        {% else %}
        - cuda-python >=12.0.0
        {% endif %}
  - name: rapids_cmake_dependency
    requirements:
      run:
        - cmake>=3.23.1,!=3.25.0
  - name: rapids_cython_dependency
    requirements:
      run:
        - cython >=0.29,<0.30
  - name: rapids_scikit_build_dependency
    requirements:
      run:
        - scikit-build>=0.13.1,<0.17.2
  # TODO: Should the grouped metapackages be named *_dependencies instead of *_dependency?
  - name: rapids_build_dependency
    requirements:
      run:
        - {{ pin_subpackage("rapids_cmake_dependency", exact=True) }}
        - {{ pin_subpackage("rapids_cython_dependency", exact=True) }}
        - ninja
        - {{ pin_subpackage("rapids_scikit_build_dependency", exact=True) }}
  - name: rapids_build_dependency
    requirements:
      run:
        - setuptools >=61.0.0
        - tomli
  - name: rapids_build_binary_dependency
    requirements:
      run:
        - {{ pin_subpackage("rapids_cmake_dependency", exact=True) }}
        - {{ pin_subpackage("rapids_cython_dependency", exact=True) }}
        - ninja
        - {{ pin_subpackage("rapids_scikit_build_dependency", exact=True) }}
  - name: rapids_dask_cuda_dependency
    requirements:
      run:
        - dask-cuda ==23.6.*
  - name: rapids_dask_dependency
    requirements:
      run:
        - dask ==2023.3.2
        - dask-core==2023.3.2
        - distributed ==2023.3.2.1
  - name: rapids_test_dependency
    requirements:
      run:
        - pytest
        - pytest-cov
        - pytest-xdist
